package com.drools.movieSelector;

import java.util.ArrayList;
import java.util.List
import com.drools.movieSelector.MovieSelector.Question
import java.awt.Component;
import javax.swing.*;
import org.kie.api.runtime.*;

global javax.swing.JFrame frame
global javax.swing.JTextArea textArea;
global javax.swing.JPanel optionsContainer;
global javax.swing.JPanel movieContainer;


query "getQuestionsWithNoAnswer"
    question : Question(answer.equals(""))
end

function void newQuestionWithAnswer(String question, String answerA, String answerB, JFrame frame, JTextArea textArea, JPanel  optionsContainer ) {

   textArea.setText(null);
   textArea.append(question + "\n");
   List<JRadioButton> buttonList = new ArrayList<>();
   ButtonGroup group = new ButtonGroup();

   buttonList.add(new JRadioButton(answerA));
   buttonList.add(new JRadioButton(answerB));

   optionsContainer.removeAll();

   for(JRadioButton button : buttonList) {
   			group.add(button);
   		}

   		for(JRadioButton button : buttonList) {
   			optionsContainer.add(button);
   		}

   		optionsContainer.revalidate();
   		optionsContainer.repaint();
}

function void createQuestion(String text, KieRuntime krt) {

   Question q = new Question();
   q.setText(text);
   q.setAnswer("");
   krt.insert(q);
}

function void showMovie(String movie, JPanel  movieContainer) {
        JLabel label1 = new JLabel();
        label1.setText(movie);
        label1.setBounds(0, 0, 200, 50);
        movieContainer.add(label1);

        movieContainer.revalidate();
        movieContainer.repaint();
}


rule "Init" // pytanie nr1
    when
    then
    	createQuestion("Anyone recently getting over breakup?", kcontext.getKieRuntime());

end

rule "start"
    when
        q : Question(q.getText().equals("Anyone recently getting over breakup?") && q.getAnswer().equals(""));
    then
    newQuestionWithAnswer(q.getText() ,"We're good!","Let's avoid the heartache", frame, textArea, optionsContainer);

end

rule "question1_A"
	when
        q : Question(q.getText().equals("Anyone recently getting over breakup?") && q.getAnswer().equals("We're good!"));
	then
        createQuestion("Do you want to cry?", kcontext.getKieRuntime());
        newQuestionWithAnswer("Do you want to cry?", "Load up on the waterproof mascara!", "I'd rather not", frame, textArea, optionsContainer);
end

rule "question1_B"
	when
        q : Question(q.getText().equals("Anyone recently getting over breakup?") && q.getAnswer().equals("Let's avoid the heartache"));
	then
		createQuestion("Would a hunky man help?", kcontext.getKieRuntime());
        newQuestionWithAnswer("Would a hunky man help?", "I prefer a mystery man", "Yes please!", frame, textArea, optionsContainer);
end

rule "question2_A"
	when
        q : Question(q.getText().equals("Would a hunky man help?") && q.getAnswer().equals("I prefer a mystery man"));
	then
        createQuestion("Do you like Tim Burton?", kcontext.getKieRuntime());
        newQuestionWithAnswer("Do you like Tim Burton?", "Bring on the darkness!", "Something less morose", frame, textArea, optionsContainer);
end

rule "question2_B"
	when
        q : Question(q.getText().equals("Would a hunky man help?") && q.getAnswer().equals("Yes please!"));
	then
		createQuestion("Is it Ryan Gosling?", kcontext.getKieRuntime());
        newQuestionWithAnswer("Is it Ryan Gosling?", "Over him", "Duh", frame, textArea, optionsContainer);
end

rule "question3_A"
	when
        q : Question(q.getText().equals("Is it Ryan Gosling?") && q.getAnswer().equals("Over him"));
	then
        createQuestion("Indie eye or classic hunks?", kcontext.getKieRuntime());
        newQuestionWithAnswer("Indie eye or classic hunks?", "Indie", "Can't argue with a classic", frame, textArea, optionsContainer);
end

rule "question3_B"
	when
        q : Question(q.getText().equals("Is it Ryan Gosling?") && q.getAnswer().equals("Duh"));
	then
		createQuestion("Is Gosling head over heels in love?", kcontext.getKieRuntime());
        newQuestionWithAnswer("Is Gosling head over heels in love?", "If it's not starring me than no", "Yes", frame, textArea, optionsContainer);
end

rule "question4_A"
	when
        q : Question(q.getText().equals("Is Gosling head over heels in love?") && q.getAnswer().equals("If it's not starring me than no"));
	then
        createQuestion("Is he a playboy?", kcontext.getKieRuntime());
        newQuestionWithAnswer("Is he a playboy?", "OK", "No, he's family man", frame, textArea, optionsContainer);
end

rule "question4_B"
	when
        q : Question(q.getText().equals("Is Gosling head over heels in love?") && q.getAnswer().equals("Yes"));
	then
        showMovie("Lars and the real girl", movieContainer);
end
